### PR TITLE
Simpler method utilizing find+bash builtins, or just zsh builtins.

### PR DESCRIPTION
**Pull request by noksookhao**
image

### CODE REVIEW

**Comment by noksookhao** [comment]
this should work with zsh:

`unsetopt CASE_GLOB && for x in ./**/*png;do cwebp -resize 800 0 "${x}" -o "${x/(png|PNG)/webp}";done; setopt CASE_GLOB`


This is nice as it gets rid of using `find` as well, making it a `zsh` one-liner :)

Edit: added to PR with commit [fa0ab6e](https://github.com/bubbafat/bubbafat.github.io/pull/2/commits/fa0ab6e6c0ec61ef49003b4b89a9eea373665a91)

image

**Comment by noksookhao** [comment]
Sorry for all the commits, doing too many things at once 🤣 

cheers! 🤙🏼🤙🏼🤙🏼🤙🏼

**Comment by noksookhao** [comment]
Confirmed to work as intended now in `zsh`. I'm a `bash` user myself, and knew what I wanted to do, just needed to figure out the correct `zsh` syntax.

Please let me know if there are any issues. it should cover everything other than (maybe) a file extension like `.PnG` or `.pnG`. 

_(No idea why anyone would use that capitalization, but figured I'd mention it.)_

**Review by bubbafat — APPROVED** [review]
Thanks - this is great!

**Pull request merged**
